

DALServiceError
==============================

.. currentmodule:: pyvo.dal.query

.. autoexception:: DALServiceError